### ISSUE TITLE
领取模块：【class: Frame】

### ISSUE THREAD

**Issue by abcdGJJ** [zhaoqize/puppeteer-api-zh_CN#11]
- 公司：58集团
- 工作内容：前端工程师
- 个人博客：https://gaojiajun.cn
- 觉得 headless 的前景如何：很有发展潜力
- 领取模块：【class: Frame】
- 翻译完成时间点：2018年6月11日

**Comment by zhaoqize** [comment]
😄 好的 ，请fork，然后在对应的目录下翻译，最后提PR即可。
