### ISSUE TITLE
page模块一个翻译错误的地方

### ISSUE THREAD

**Issue by normalHamal** [zhaoqize/puppeteer-api-zh_CN#16]
- 模块：class: Page
- 修改内容：
  #### page.$$(selector)
  - `selector` <[string]> 选择器
  - 返回: <[Promise]<[Array]<[ElementHandle]>>>

  此方法在页面内执行~~document.querySelector~~`document.querySelectorAll`。如果没有元素匹配指定选择器，返回值是`[]`。

  [page.mainFrame().$$(selector)](#frameselector-1)的简写。

- 官方链接：

  [page.$$(selector)](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageselector-1)

**Comment by zhaoqize** [comment]
已修改 😀

**Comment by ilaipi** [comment]
@normalHamal 
😅可能是复制前面的一段，这句忘记修改了
