### ISSUE TITLE
领取模块: 【class: BrowserFetcher】

### ISSUE THREAD

**Issue by 15vTechAdmin** [zhaoqize/puppeteer-api-zh_CN#2]
* 公司：自由职业者
* 工作内容：全栈
* 个人博客：https://blog.vvvvvvvvvvvvvvv.com/
* 觉得 headless 的前景如何：自动化测试大有可为
* 领取模块: 【class: BrowserFetcher】
* 翻译完成时间点：2018年6月1号

**Comment by zhaoqize** [comment]
@15vTechAdmin 好的 😄 ，请fork，然后在对应的目录下翻译，最后提PR即可
