### ISSUE TITLE
领取模块: 【class: Request】

### ISSUE THREAD

**Issue by Gavin-Gong** [zhaoqize/puppeteer-api-zh_CN#3]
- 公司：某小公司
- 工作内容：前端
- 个人博客：https://gavin-gong.github.io/note
- 领取模块: 【class: Request】
- 翻译完成时间点：2018年5月28号

**Comment by zhaoqize** [comment]
@Gavin-Gong 好的 😄 ，请fork，然后在对应的目录下翻译，最后提PR即可。
