### ISSUE TITLE
翻译改善建议

### ISSUE THREAD

**Issue by Aaron-Bird** [zhaoqize/puppeteer-api-zh_CN#31]
- 模块：page.hover(selector)
- 修改内容：
<del>
此方法找到一个匹配的元素，如果需要会把此元素滚动到可视，然后通过 page.mouse 来hover到元素的中间。 如果没有匹配的元素，此方法将会报错。
</del>

此方法使用 selector 匹配元素.如有必要,会将匹配到的元素滚动到视口中.然后使用 page.mouse 将鼠标悬停在元素的中心位置.如果 selector 没有匹配到元素,则抛出一个错误.

**Comment by zhaoqize** [comment]
@Aaron-Bird 老哥，PR 👏
