### ISSUE TITLE
领取模块：【class: Page】

### ISSUE THREAD

**Issue by ilaipi** [zhaoqize/puppeteer-api-zh_CN#4]
公司：上海瓴豆（小公司）
工作内容：后端开发（前端辅助）
个人博客：http://ilaipi.github.io
觉得 headless 的前景如何：自动测试，爬虫比较有用
领取模块: 【class: Page】
翻译完成时间点：2018年6月25号

**Comment by zhaoqize** [comment]
@ilaipi 好的 😄 ，请fork，然后在对应的目录下翻译，最后提PR即可。
