### ISSUE TITLE
请求认领 class: Browser

### ISSUE THREAD

**Issue by easyxin** [zhaoqize/puppeteer-api-zh_CN#5]
* 公司：北京瑞达恒建筑咨询有限公司(上海分公司)
* 工作内容：后端开发
* 个人博客：http://blog.jiangyixin.top/
* 觉得 headless 的前景如何：Google领头发展，潜力大
* 领取模块: 【class: Browser】
* 翻译完成时间点：2018年5月20号

**Comment by zhaoqize** [comment]
@jiangyx3915 好的 😄 ，请fork，然后在对应的目录下翻译，最后提PR即可。
